breaking(service): update Service

diff --git a/.github/workflows/docker-build.yaml b/.github/workflows/docker-build.yaml
--- a/.github/workflows/docker-build.yaml
+++ b/.github/workflows/docker-build.yaml
@@ -24,7 +24,7 @@ on:
   #   branches:
   #     - main
   workflow_run:
-    workflows: ['Continuous Integration – Omnixys']
+    workflows: ['Release Service']
     types: [completed]
 
   workflow_dispatch:
@@ -50,6 +50,7 @@ env:
   OMNIXYS_USER_USERNAME: ${{ secrets.OMNIXYS_USER_USERNAME }}
   OMNIXYS_USER_PASSWORD: ${{ secrets.OMNIXYS_USER_PASSWORD }}
   OMNIXYS_EMAIL_DOMAIN: ${{ secrets.OMNIXYS_EMAIL_DOMAIN }}
+  OMNIXYS_TOKEN: ${{ secrets.OMNIXYS_TOKEN }}
 
   KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}
   TEMPO_URI: ${{ secrets.TEMPO_URI }}
@@ -62,7 +63,6 @@ env:
   KC_CLIENT_SECRET: ${{ secrets.KC_CLIENT_SECRET }}
 
   KEYS_PATH: ${{ secrets.KEYS_PATH }}
-
   SERVICE: ${{ vars.SERVICE }}
   PORT: ${{ secrets.PORT }}
   GRAPHQL_PLAYGROUND: ${{ secrets.GRAPHQL_PLAYGROUND }}
@@ -74,9 +74,6 @@ env:
   LOG_DEFAULT: ${{ secrets.LOG_DEFAULT }}
   LOG_DIRECTORY: ${{ secrets.LOG_DIRECTORY }}
   LOG_FILE_DEFAULT_NAME: ${{ secrets.LOG_FILE_DEFAULT_NAME }}
-
-  DATABASE_URL: ${{ secrets.DATABASE_URL }}
-  SHADOW_DATABASE_URL: ${{ secrets.SHADOW_DATABASE_URL }}
 
 jobs:
   push-docker:
@@ -90,6 +87,28 @@ jobs:
     steps:
       - name: 🧾 Checkout repository
         uses: actions/checkout@v4
+
+      - name: Setup npm registry auth
+        run: |
+          echo "@omnixys:registry=https://npm.pkg.github.com" >> .npmrc
+          echo "//npm.pkg.github.com/:_authToken=${OMNIXYS_TOKEN}" >> .npmrc
+        env:
+          OMNIXYS_TOKEN: ${{ secrets.OMNIXYS_TOKEN }}
+
+      - name: 🔎 Check if Docker tag already exists
+        id: check_tag
+        run: |
+          set -e
+
+          echo "Checking if tag exists: $IMAGE_NAME:${CURRENT_VERSION}"
+
+          if docker manifest inspect "$IMAGE_NAME:${CURRENT_VERSION}" > /dev/null 2>&1; then
+            echo "Tag exists → skipping build"
+            echo "exists=true" >> $GITHUB_OUTPUT
+          else
+            echo "Tag does not exist → build required"
+            echo "exists=false" >> $GITHUB_OUTPUT
+          fi
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -112,8 +131,11 @@ jobs:
             buildx-
 
       - name: Build and Push Docker Image (Multi-Arch)
+        if: steps.check_tag.outputs.exists == 'false'
         uses: docker/build-push-action@v5
         with:
+          secrets: |
+            omnixys_token=${{ env.OMNIXYS_TOKEN }}
           context: .
           push: true
           platforms: linux/amd64,linux/arm64
@@ -131,8 +153,6 @@ jobs:
             APP_VERSION=${{ env.CURRENT_VERSION }}
             APP_NAME=${{ vars.SERVICE }}
             NODE_VERSION=${{ matrix.node-version }}
-            SHADOW_DATABASE_URL=${{ env.SHADOW_DATABASE_URL }}
-            DATABASE_URL=${{ env.DATABASE_URL }}
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache
 
@@ -140,6 +160,7 @@ jobs:
         uses: sigstore/cosign-installer@v3
 
       - name: Sign Docker Image with cosign (OIDC/GitHub)
+        if: steps.check_tag.outputs.exists == 'false'
         run: |
           cosign sign --yes --recursive ${{ env.IMAGE_NAME }}:${{ env.CURRENT_VERSION }}
           cosign sign --yes --recursive ${{ env.IMAGE_NAME }}:latest
@@ -155,6 +176,21 @@ jobs:
     steps:
       - name: 🧾 Checkout repository
         uses: actions/checkout@v4
+
+      - name: 🔎 Check if Docker tag already exists
+        id: check_tag
+        run: |
+          set -e
+
+          echo "Checking if tag exists: $IMAGE_NAME:${CURRENT_VERSION}"
+
+          if docker manifest inspect "$IMAGE_NAME:${CURRENT_VERSION}" > /dev/null 2>&1; then
+            echo "Tag exists → skipping build"
+            echo "exists=true" >> $GITHUB_OUTPUT
+          else
+            echo "Tag does not exist → build required"
+            echo "exists=false" >> $GITHUB_OUTPUT
+          fi
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -178,8 +214,11 @@ jobs:
             buildx-
 
       - name: Build and Push Docker Image (GHCR)
+        if: steps.check_tag.outputs.exists == 'false'
         uses: docker/build-push-action@v5
         with:
+          secrets: |
+            omnixys_token=${{ env.OMNIXYS_TOKEN }}
           context: .
           push: true
           platforms: linux/amd64,linux/arm64
@@ -197,8 +236,6 @@ jobs:
             APP_VERSION=${{ env.CURRENT_VERSION }}
             APP_NAME=${{ vars.SERVICE }}
             NODE_VERSION=${{ matrix.node-version }}
-            SHADOW_DATABASE_URL=${{ env.SHADOW_DATABASE_URL }}
-            DATABASE_URL=${{ env.DATABASE_URL }}
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache
 
@@ -206,6 +243,7 @@ jobs:
         uses: sigstore/cosign-installer@v3
 
       - name: Sign Docker Image with cosign (OIDC/GitHub)
+        if: steps.check_tag.outputs.exists == 'false'
         run: |
           cosign sign --yes --recursive ${{ env.IMAGE_NAME_REPOSITORY }}:${{ env.CURRENT_VERSION }}
           cosign sign --yes --recursive ${{ env.IMAGE_NAME_REPOSITORY }}:latest
